// task09-react/src/components/IslandSection.js
import React, { Component } from 'react';
import Island from './Island';
import dawn from '../assets/img/dawn.svg';
import reverse from '../assets/img/reverse.svg';

class IslandSection extends Component {
  islands = [{ name: "Dawn Island", location: "East Blue", img: dawn},
             { name: "Reverse Island", location: "Red Line", img: reverse},
             { name: "Reverse Island", location: "Red Line", img: reverse}];
  renderIslands() {
    return this.islands.map((i, index) => {
      return <Island key={index} name={i.name} location={i.location} img={i.img} alt={i.name}/>;
    });
  }
  render() { 
    return (
      <article className="article article--islands">
        <div className="article__container article__container--islands">
          <h3 className="article__title article__title--island">Islands</h3>
          <a href="#" className="article__link article__link--islands">See all</a>
        </div>
        <div className="article__flex article__flex--islands">
          {this.renderIslands()}
        </div>
      </article>
    );
  }
}
 
export default IslandSection;

// task10-vue/src/components/IslandSection.vue
<template>
  <article class="article article--islands">
    <div class="article__container article__container--islands">
      <h3 class="article__title article__title--island">Islands</h3>
      <a href="#" class="article__link article__link--islands">See all</a>
    </div>
    <div class="article__flex article__flex--islands">
      <IslandCard
        v-for="(island, index) in islands"
        :key="index"
        :name="island.name"
        :img="island.img"
        :location="island.location"
      />
    </div>
  </article>
</template>

<script>
  import IslandCard from './IslandCard.vue'
  export default {
    name: 'IslandsSection',
    components: {
      IslandCard,
    },
    data() {
      return {
        islands: [{ name: 'Dawn Island', location: 'East Blue', img: require('../assets/dawn.svg')},
                  { name: 'Reverse Island', location: 'Red Line', img: require('../assets/reverse.svg')},
                  { name: 'Reverse Island', location: 'Red Line', img: require('../assets/reverse.svg')}],
      }
    },
  }
</script>
