// task10-vue/src/components/CharacterSection.vue
<template>
  <article class="article article--characters">
    <div class="article__container article__container--characters">
      <h3 class="article__title article__title--characters">Characters</h3>
      <a href="#" class="article__link article__link--characters">See all</a>
    </div>
    <div class="article__flex article__flex--characters">
      <CharacterCard
        v-for="character in characters"
        :key="character.name"
        :name="character.name"
        :img="character.img"
      />
    </div>
  </article>
</template>

<script>
  import CharacterCard from './CharacterCard.vue';
  export default {
    name: 'CharacterSection',
    components: {
      CharacterCard,
    },
    
    data() {
      return {
        characters : [{ name: 'Monkey D. Luffy', img: require('../assets/monkeydluffy.svg')},
                      { name: 'Portgas D. Ace', img: require('../assets/ace.svg')},
                      { name: 'Roronoa Zoro', img: require('../assets/zoro.svg')},
                      { name: 'Nico Robin', img: require('../assets/nico.svg')}]
      }
    }
  }
</script>

// task09-react/src/components/CharacterSection.js
import React, { Component } from 'react';
import Character from './Character';
import luffy from '../assets/img/monkeydluffy.svg';
import ace from '../assets/img/ace.svg';
import zoro from '../assets/img/zoro.svg';
import nico from '../assets/img/nico.svg';

class CharacterSection extends Component {
  render() { 
    return (
      <article className="article article--characters">
        <div className="article__container article__container--characters">
          <h3 className="article__title article__title--characters">Characters</h3>
          <a href="#" className="article__link article__link--characters">See all</a>
        </div>
        <div className="article__flex article__flex--characters">
          <Character name="Monkey D. Luffy" img={luffy} alt="Monkey D. Luffy" />
          <Character name="Portgas D. Ace" img={ace} alt="Ace" />
          <Character name="Roronoa Zoro" img={zoro} alt="Zoro" />
          <Character name="Nico Robin" img={nico} alt="Nico Robin" />
        </div>
      </article>
    );
  }
}
 
export default CharacterSection;
